branch-defaults:
  default:
    environment: embarkscout
global:
  application_name: embarkscout
  default_ec2_keyname: embarkscout
  default_platform: Python 3.4
  default_region: us-east-1
  profile: null
  sc: null
